const questions = {
  "Restricted_Repetitive_Behavior" : [
    "If left alone, the majority of the individuals time will be spent in repetitive or stereotyped behaviors.",
    "Is preoccupied with specific stimuli that are abnormal in intensity.",
    "Stares at hands, objects, or items in the enviornment for at least 5 seconds.",
    "Flicks fingers rapidly in front of eyes for periods of 5 seconds or more.",
    "Makes rapid lunging, darting movements when moving from place to place.",
    "Flaps hands or fingers in front of face or at sides."
    "Make high-pitched sounds (e.g., eee-eee-eee-eee) or other vocalizations for self-stimulatoin.",
    "Uses toys or objects inappropriately (e.g., spins cars, takes actions toys apart).",
    "Does certain things repetitiverly, ritualistically.",
    "Engages in stereotyped behaviours when playing with toys or obejcts.",
    "Repeats unintelligible sounds (babbles) over and over.",
    "Shows unusual interest in sensory aspects of play materials, body parts, or objects.",
    "Displays ritualistic or compulsive behaviors.",
  ],
  "Social_Interaction": [
    "Does not initiate converstions with peers or others.",
    "Pays little or no attention to what peers are doing.",
    "Fails to imitate other people in games or learning activities.",
    "Does not follow others gestures(cues) to look at something (e.g., when other person nods head, points, or use other language cues.)",
    "Seems indifferent to other persons attention (does not try to get, maintain, or direct the other persons attention.)",
    "Shows minimal expressed pleasure when interacting with others.",
    "Displays little or no excitement in showing toys or objects to others.",
    "Seems uninterested in pointing out things in the environment to others.",
    "Seems unwilling or reluctant to get others to interact with him or her.",
    "Shows minimal or no response when others attempt to interact with him or her.",
    "Displays little or no reciprocal social communication(e.g., deso not voluntarily say bye-bye in response to another saying bye-bye to him or her.",
    "Does not try to make frients with other people.",
    "Fails to engage in creative, imaginative play.",
    "Shows little or no interest in other people.",
  ],
  "Social_Communication": [
    "Responds inappropriately to humorous stimuli(e.g., does not laugh at jokes, cartoons, funny stories).",
    "Has difficulty understanding jokes.",
    "Has difficulty understanding slang expressions.",
    "Has difficulty identifying when someone is teasing.",
    "Has difficulty understanding when he or she is being ridiculed.",
    "Has difficulty understanding what causes people to dislike him or her.",
    "Fails to predict probable consequences in social events.",
    "Does not seem to understand that people have thoughts and feeelings different from hisor hers.",
    "Does not seem to understand that the other person does not know something.",
  ],
  "Emotional Responses": [
    "Needs an excessive amount of reassurance if things are changed or go wrong.",
    "Becomes frustrated quickly when he or she cannot do something.",
    "Temper tantrums when frustrated.",
    "Becomes upset when routines are changed.",
    "Responds negatively when given commands, request, or directions,",
    "Has exterem reactions (e.g., cries, screams, tantrums) in response to loud, unexpected noise.",
    "Temper tantrums when does not get his or her way.",
    "Temper tantrums when told to stop doing something he or she enjoys doing.",
  ],
  "Congnitive Style": [
    "Uses exceptionally precise speech.",
    "Attaches very concrete meanings to words.",
    "Talks about a single subject excessively.",
    "Displays superior knowledge or skill in specific subjects.",
    "Displays excellent memory.",
    "Shows an intense, obsessive interest in specific intellectual subjects.",
    "Makes naïve remarks (unaware of reaction produced in others).",
  ],
  "Maladaptive Speech": [
    "Repeats (echoes) words or phrases verbally or with signs.",
    "Repeats words out of context ( repeats words or phrases heard at an earlier time).",
    "Speaks (or sign) with flat tone, affect.",
    "Uses yes and no inappropriately. Says yes when asked if he or she wants an aversive stimulus or says no when he or she want a favorite toy or treat.",
    "Uses he or she instead of I when referring to self.",
    "Speech is abnormal in tone, volumn, or rate.",
    "Utters idiosyncratic words or phrases that have no meaning to others.",
  ],
};